name: Build Avalonia App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64, osx-arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate version
        id: version
        shell: bash
        run: |
          VERSION="1.0.0-preview.$(date +%y%m%d%H%M)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Publish Avalonia App
        run: |
          dotnet publish src/AvaloniaWeather/AvaloniaWeather.csproj \
            -c Release \
            -r ${{ matrix.os }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:DebugType=None \
            -p:DebugSymbols=false \
            -o publish/${{ matrix.os }} \
            /p:Version=${{ env.VERSION }}

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AvaloniaWeather-${{ matrix.os }}-${{ env.VERSION }}
          path: publish/${{ matrix.os }}
